import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/provider/theme-provider'
import GlobalAppStateProvider from '@/provider/global-app-state-provider'
import { cn } from '@/lib/utils'
import App from '../App'
import Navbar from '@/components/custom/navbar'
import WorkspaceControl from '@/components/custom/workspace-control'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trello',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={cn('', inter.className)}>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <GlobalAppStateProvider>
              <App>
                <div className='h-full w-full'>
                  <div className='h-[10%]'>
                    <Navbar />
                    <WorkspaceControl />
                  </div>
                  <div className='h-[90%]'>{children}</div>
                </div>
              </App>
            </GlobalAppStateProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
